### PR TITLE
feat: CORE-1541 - Add streamr-client tests to Travis CI

### PR DESCRIPTION
**Pull request by mikhaelsantos**
* Add .travis.yml file

### CODE REVIEW

**Comment by hpihkala** [comment]
@mikhaelsantos Tests not passing! Is it actually the case, or sth wrong with the setup?

**Comment by harbu** [comment]
Getting same error on my machine. Problem with tests/code/setup not Travis.

**Comment by hpihkala** [comment]
@mikhaelsantos @Aapzu Tests refactored, fixed, and moved to jest. Everything now passing on my machine at least. Fingers crossed for Travis.

**Comment by mikhaelsantos** [comment]
Even-though failing, I am merging this because it adds the travis file making it easier for anyone to fix the issue.

**Comment by hpihkala** [comment]
Remember to squash merge please!

**Pull request merged**
